### ISSUE TITLE
Error Exception in Proxy.php

### ISSUE THREAD

**Issue by dabiddo** [esbenp/lumen-api-oauth#13]
Hello

I tried running your example but I get an error when requesting a token
ErrorException in Proxy.php line 46:
First parameter must either be an object or the name of an existing class

at property_exists(null, 'access_token') in Proxy.php line 46

I tried changing the line from:
$guzzleResponse->getBody(); 
$guzzleResponse->getBody()->getContents();

But the guzzleResponse is always null,

Can you please help me with this error?

Regards

**Comment by gitpug23** [comment]
I got the same error also.

**Comment by dabiddo** [comment]
Install Memcached and restart Apache/Nginx on your server, that worked for me! :)
