### ISSUE TITLE
How to make dynamic login ?

### ISSUE THREAD

**Issue by prashantidealittechno** [esbenp/lumen-api-oauth#17]
Can anybody help me to make it dynamic login, currently in client.js file has following code -
 url: "/index.php/login",
        method: "POST",
        data: {
            credentials: {
                username: 'user@user.com',
                password: '1234'
            }
        }, 

I want to set username = whatever I post and same for the password.

I just want to call it through - postman
like -
http://wikilocal.mysite.com/index.php/login
method - post
parameters -
username - any-user-name
password - my-password

is it possible ?

Thank you.

**Comment by esbenp** [comment]
If you mean when having a form, you could just reference the fields value in the client.js

**client.js**

```
url: "/index.php/login",
method: "POST",
data: {
credentials: {
username: document.getElementById('email').value,
password: document.getElementById('password').value
}
},
```
