### ISSUE TITLE
Is there any way to generate access token when sign up with facebook or twitter or google?

### ISSUE THREAD

**Issue by prashantidealittechno** [esbenp/lumen-api-oauth#19]
Hello,
Can anybody help me to customize it? I need to issue access token when user logs in with facebook or twitter or google.In my API request I get id parameter which holds value for facebook or google or twitter, I check this id in database and return its result if exists but I want to generate access token along with user info.
If anybody have idea, it would be really appreciated.

Thank you.

**Comment by zohaibmir** [comment]
its very simple just call  the attemptLogin() method from your facebook signup method or where ever you want to generate the token.
