### ISSUE TITLE
"invalid_client" when logging in with sample.

### ISSUE THREAD

**Issue by Pitu** [esbenp/lumen-api-oauth#21]
Hi esbenp, really nice app here. I read your article a few weeks back and now I downloaded it from here to fiddle with it a bit. 

Unfortunately when I try to log in with the buttons and js libraries you procured I get a

```
{"error":"invalid_client","error_description":"Client authentication failed."}
```

as a response. I migrated al the tables and my 'users' table has one entry with 'user@user.com' as email and an encrypted password which I guess is '1234' after reading your client.js.

I'd appreciate it if you could help me out here a bit.
Thanks and amazing work!

**Comment by rakesh-ideal** [comment]
Hello @pituseligmann , please make sure your composer.josn file has -
` "require": {
        "php": ">=5.5.9",
        "laravel/lumen-framework": "5.1.*",
        "vlucas/phpdotenv": "~1.0",
        "optimus/oauth2-server-lumen": "0.1.*",
        "guzzlehttp/guzzle": "^6.1"
    },`

And .env file has -
`CACHE_DRIVER=memcached
SESSION_DRIVER=cookie
QUEUE_DRIVER=database`

and also check you have 'Memcached' install on your machine.

**Comment by rakesh-ideal** [comment]
Hello @pituseligmann , please make sure your composer.josn file has -
` "require": {
        "php": ">=5.5.9",
        "laravel/lumen-framework": "5.1.*",
        "vlucas/phpdotenv": "~1.0",
        "optimus/oauth2-server-lumen": "0.1.*",
        "guzzlehttp/guzzle": "^6.1"
    },`

And .env file has -
`CACHE_DRIVER=memcached
SESSION_DRIVER=cookie
QUEUE_DRIVER=database`

and also check you have 'Memcached' install on your machine.

**Comment by prashantidealittechno** [comment]
Hello @pituseligmann , please make sure your composer.josn file has -
`"require": {
        "php": ">=5.5.9",
        "laravel/lumen-framework": "5.1.*",
        "vlucas/phpdotenv": "~1.0",
        "optimus/oauth2-server-lumen": "0.1.*",
        "guzzlehttp/guzzle": "^6.1"
    },`

And .env file has -
`CACHE_DRIVER=memcached
SESSION_DRIVER=cookie
QUEUE_DRIVER=database`

and also check you have 'Memcached' install on your machine.
