### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by sparkidea** [esbenp/lumen-api-oauth#4]
I am getting 500 Internal Server Error, whenver i hit the login button.
and in Inspect Element it shows: 

{}

Nothing else than this!

**Comment by esbenp** [comment]
Did you run migrations and database seeding like this: https://github.com/esbenp/lumen-api-oauth/issues/1#issuecomment-105997199 ?

**Comment by esbenp** [comment]
I just pushed some commits to the repo. Try cloning these and then follow the instructions again.
