### ISSUE TITLE
Missing argument 1 for Illuminate\\Auth\\AuthManager::createDriver()

### ISSUE THREAD

**Issue by codivist** [esbenp/lumen-api-oauth#7]
when trying to login via /login (proxy) everything is working, except inside the callback of the password grant type, I get the following error:
`Missing argument 1 for Illuminate\\Auth\\AuthManager::createDriver() , called in /srv/www/api.mydevtest.dev/deploy/vendor/illuminate/support/Manager.php on line 87`

I'm using the credentials used in the seeder.  Is there something else I need in the call back?

**Comment by esbenp** [comment]
Did you add an env file? I have added an example file here https://github.com/esbenp/lumen-api-oauth/blob/master/.env.example 

Just rename it to `.env` in your root directory and change to your settings

**Comment by esbenp** [comment]
Close due to inactivity
